<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subjects = [
            ['code' => 'A0672', 'name' => 'Praktikum Sistem eBusiness'],
            ['code' => 'COMP6016', 'name' => 'Website Design'],
            ['code' => 'COMP6045', 'name' => 'Algorithm & Programming'],
            ['code' => 'COMP6047001', 'name' => 'Algorithm and Programming'],
            ['code' => 'COMP6047', 'name' => 'Algorithm and Programming'],
            ['code' => 'COMP6048', 'name' => 'Data Structures'],
            ['code' => 'COMP6051', 'name' => 'Web Programming'],
            ['code' => 'COMP6064', 'name' => 'Geographical Information System'],
            ['code' => 'COMP6099', 'name' => 'Advanced Object Oriented Programming'],
            ['code' => 'COMP6102', 'name' => 'Algorithm and Programming'],
            ['code' => 'COMP6106', 'name' => 'Code Reengineering'],
            ['code' => 'COMP6114', 'name' => 'Pattern Software Design'],
            ['code' => 'COMP6115001', 'name' => 'Object Oriented Analysis & Design'],
            ['code' => 'COMP6115', 'name' => 'Object Oriented Analysis & Design'],
            ['code' => 'COMP6119', 'name' => 'Database Administration'],
            ['code' => 'COMP6120', 'name' => 'Network Programming'],
            ['code' => 'COMP6122001', 'name' => 'Framework Layer Architecture'],
            ['code' => 'COMP6122', 'name' => 'Framework Layer Architecture'],
            ['code' => 'COMP6132', 'name' => 'Linux Operating System'],
            ['code' => 'COMP6140001', 'name' => 'Data Mining'],
            ['code' => 'COMP6140', 'name' => 'Data Mining'],
            ['code' => 'COMP6144001', 'name' => 'Web Programming'],
            ['code' => 'COMP6144', 'name' => 'Web Programming'],
            ['code' => 'COMP6153001', 'name' => 'Operating System'],
            ['code' => 'COMP6153', 'name' => 'Operating System'],
            ['code' => 'COMP6154', 'name' => 'Algorithm and Programming Fundamentals'],
            ['code' => 'COMP6175', 'name' => 'Object Oriented Programming'],
            ['code' => 'COMP6176001', 'name' => 'Human and Computer Interaction'],
            ['code' => 'COMP6176', 'name' => 'Human and Computer Interaction'],
            ['code' => 'COMP6178003', 'name' => 'Introduction to Programming'],
            ['code' => 'COMP6178', 'name' => 'Introduction to Programming '],
            ['code' => 'COMP6181', 'name' => 'Cyber Security Analysis and Method'],
            ['code' => 'COMP6183', 'name' => 'Secure Web Programming'],
            ['code' => 'COMP6193', 'name' => 'Cyber Forensic'],
            ['code' => 'COMP6225', 'name' => 'Object Oriented Database'],
            ['code' => 'COMP6226001', 'name' => 'Competitive Programming'],
            ['code' => 'COMP6226', 'name' => 'Competitive Programming'],
            ['code' => 'COMP6231', 'name' => 'Human and Computer Interaction'],
            ['code' => 'COMP6232001', 'name' => 'Human and Computer Interaction'],
            ['code' => 'COMP6232', 'name' => 'Human and Computer Interaction'],
            ['code' => 'COMP6233', 'name' => 'Website Design'],
            ['code' => 'COMP6268', 'name' => 'Algorithm & Programming'],
            ['code' => 'COMP6405', 'name' => 'Website Design'],
            ['code' => 'COMP6458', 'name' => 'Data Structures'],
            ['code' => 'COMP6543001', 'name' => 'Secure Programming'],
            ['code' => 'COMP6543', 'name' => 'Secure Programming'],
            ['code' => 'COMP6544001', 'name' => 'Network Penetration Testing'],
            ['code' => 'COMP6544', 'name' => 'Network Penetration Testing'],
            ['code' => 'COMP6546', 'name' => 'Network Administration'],
            ['code' => 'COMP6548001', 'name' => 'Programming for Penetration Testing'],
            ['code' => 'COMP6548', 'name' => 'Programming for Penetration Testing'],
            ['code' => 'COMP6579001', 'name' => 'Big Data Processing'],
            ['code' => 'COMP6579', 'name' => 'Big Data Processing'],
            ['code' => 'COMP6580', 'name' => 'Database Administration'],
            ['code' => 'COMP6583001', 'name' => 'Computer Graphics'],
            ['code' => 'COMP6583', 'name' => 'Computer Graphics'],
            ['code' => 'COMP6584', 'name' => 'Network and System Programming'],
            ['code' => 'COMP6585', 'name' => 'System Administration'],
            ['code' => 'COMP6590001', 'name' => 'Geographical Information System'],
            ['code' => 'COMP6590', 'name' => 'Geographical Information System'],
            ['code' => 'COMP6591', 'name' => 'Portable Operating System Interface'],
            ['code' => 'COMP6647', 'name' => 'Web Programming'],
            ['code' => 'COMP6681001', 'name' => 'Web Programming'],
            ['code' => 'COMP6681', 'name' => 'Web Programming'],
            ['code' => 'COMP6683', 'name' => 'Introduction to Artificial Intelligence'],
            ['code' => 'COMP6708016', 'name' => 'Object Oriented Programming'],
            ['code' => 'COMP6708', 'name' => 'Object Oriented Programming'],
            ['code' => 'COMP6711', 'name' => 'Distributed Cloud Computing'],
            ['code' => 'COMP6714', 'name' => 'Introduction to Programming'],
            ['code' => 'COMP7066', 'name' => 'Expert Systems'],
            ['code' => 'COMP7067', 'name' => 'Computer Vision'],
            ['code' => 'COMP7084', 'name' => 'Multimedia Systems'],
            ['code' => 'COMP7094', 'name' => 'Multimedia Programming Foundation'],
            ['code' => 'COMP7110', 'name' => 'Computer Graphic'],
            ['code' => 'COMP7116001', 'name' => 'Computer Vision'],
            ['code' => 'COMP7116', 'name' => 'Computer Vision'],
            ['code' => 'COMP7117', 'name' => 'Artificial Neural Network'],
            ['code' => 'COMP7126', 'name' => 'Artificial Intelligence in Games'],
            ['code' => 'COMP7139', 'name' => 'Game Programming'],
            ['code' => 'COMP7142', 'name' => 'Popular Network Technology'],
            ['code' => 'COMP8108', 'name' => 'Natural Language Processing'],
            ['code' => 'COMP8129', 'name' => 'User Experience'],
            ['code' => 'CPEN6043', 'name' => 'Network Management'],
            ['code' => 'CPEN6046', 'name' => 'Computer Networks'],
            ['code' => 'CPEN6098001', 'name' => 'Computer Networks'],
            ['code' => 'CPEN6098', 'name' => 'Computer Networks'],
            ['code' => 'CPEN6101', 'name' => 'Advanced Network Programming'],
            ['code' => 'CPEN6102', 'name' => 'Network Security Administration'],
            ['code' => 'CPEN6108', 'name' => 'Computer Networks'],
            ['code' => 'CPEN6109', 'name' => 'Computer Networks'],
            ['code' => 'CPEN6220', 'name' => 'Computer Networks & Information Security'],
            ['code' => 'CPEN8076', 'name' => 'Network Security Fundamental'],
            ['code' => 'D0554', 'name' => 'Algoritma dan Pemrograman Komputer'],
            ['code' => 'GAME6004', 'name' => 'Object Oriented Game Programming'],
            ['code' => 'GAME6012', 'name' => 'User Experiences'],
            ['code' => 'GAME6043', 'name' => '3D Modeling for Games'],
            ['code' => 'GAME6050', 'name' => 'Game Engine Programming'],
            ['code' => 'GAME7029', 'name' => '2D Game Programming'],
            ['code' => 'GAME7044', 'name' => '2D Animation'],
            ['code' => 'GAME7045', 'name' => 'Mobile & Web Game Programming'],
            ['code' => 'H0174', 'name' => 'Computer Network'],
            ['code' => 'H0281', 'name' => 'Praktikum Sistem Berbasis Pengetahuan'],
            ['code' => 'H0483', 'name' => 'Network Programming'],
            ['code' => 'H0493', 'name' => 'Network Management'],
            ['code' => 'H0503', 'name' => 'Network Security'],
            ['code' => 'H0515', 'name' => 'Computer Networks'],
            ['code' => 'H0532', 'name' => 'Computer Network'],
            ['code' => 'H0644', 'name' => 'High Level Programming Language'],
            ['code' => 'H0666', 'name' => 'Digital Signal Processing'],
            ['code' => 'H0763', 'name' => 'Database Design and Application'],
            ['code' => 'H0794', 'name' => 'Mobile Application Development'],
            ['code' => 'H0833', 'name' => 'Network Security Fundamental'],
            ['code' => 'H0932', 'name' => 'High Level Programming Language'],
            ['code' => 'ISYS6078010', 'name' => 'Database Design and Application'],
            ['code' => 'ISYS6078', 'name' => 'Database Design and Application'],
            ['code' => 'ISYS6084', 'name' => 'Database'],
            ['code' => 'ISYS6123003', 'name' => 'Introduction to Database Systems'],
            ['code' => 'ISYS6123', 'name' => 'Introduction to Database Systems'],
            ['code' => 'ISYS6125', 'name' => 'Data warehouse'],
            ['code' => 'ISYS6169001', 'name' => 'Database Systems'],
            ['code' => 'ISYS6169', 'name' => 'Database Systems'],
            ['code' => 'ISYS6170', 'name' => 'Data Warehouse'],
            ['code' => 'ISYS6172049', 'name' => 'Database Design'],
            ['code' => 'ISYS6172', 'name' => 'Database Design'],
            ['code' => 'ISYS6197003', 'name' => 'Business Application Development'],
            ['code' => 'ISYS6197', 'name' => 'Business Application Development'],
            ['code' => 'ISYS6200003', 'name' => 'Data Warehouse'],
            ['code' => 'ISYS6200', 'name' => 'Data Warehouse'],
            ['code' => 'ISYS6203003', 'name' => 'Mobile Application Development'],
            ['code' => 'ISYS6203', 'name' => 'Mobile Application Development'],
            ['code' => 'ISYS6211003', 'name' => 'Web Based Application Development'],
            ['code' => 'ISYS6211', 'name' => 'Web based Application Development'],
            ['code' => 'ISYS6279001', 'name' => 'Database Systems'],
            ['code' => 'ISYS6279', 'name' => 'Database Systems'],
            ['code' => 'ISYS6280', 'name' => 'Database Systems'],
            ['code' => 'ISYS7155', 'name' => 'Applied Database I'],
            ['code' => 'ISYS7156', 'name' => 'Applied Database II'],
            ['code' => 'ISYS7157', 'name' => 'Applied Database III'],
            ['code' => 'J0524', 'name' => 'Perancangan Situs Web'],
            ['code' => 'J0524', 'name' => 'Website Design'],
            ['code' => 'J0974', 'name' => 'Database'],
            ['code' => 'K0742', 'name' => 'Scientific Computing Lab'],
            ['code' => 'K0813', 'name' => 'Computer Vision'],
            ['code' => 'L0182', 'name' => 'Web & Animation Design'],
            ['code' => 'M0064', 'name' => 'Programming I'],
            ['code' => 'M0074', 'name' => 'Programming II'],
            ['code' => 'M0094', 'name' => 'Introduction to Database Systems'],
            ['code' => 'M0114', 'name' => 'Web Based Programming'],
            ['code' => 'M0194', 'name' => 'Advanced Web Based Programming'],
            ['code' => 'M0462', 'name' => 'Programming I'],
            ['code' => 'M0472', 'name' => 'Praktikum Programming I'],
            ['code' => 'M0482', 'name' => 'Praktikum Web Based Programming'],
            ['code' => 'M0482', 'name' => 'Web Based Programming'],
            ['code' => 'M0482', 'name' => 'Web Based Programming Laboratories'],
            ['code' => 'M0512', 'name' => 'Praktikum Programming II'],
            ['code' => 'M0512', 'name' => 'Programming II Laboratory'],
            ['code' => 'M0522', 'name' => 'Adv. Web Based Programming'],
            ['code' => 'M0522', 'name' => 'Advanced Web Based Programming Laboratory'],
            ['code' => 'M0564', 'name' => 'Introduction to Database Systems'],
            ['code' => 'M0584', 'name' => 'Datawarehouse'],
            ['code' => 'M0614', 'name' => 'Data Mining & Online Analytical Processing (OLAP)'],
            ['code' => 'M0644', 'name' => 'Applied Database I'],
            ['code' => 'M0654', 'name' => 'Applied Database II'],
            ['code' => 'M0664', 'name' => 'Applied Database III'],
            ['code' => 'M0744', 'name' => 'Database Management'],
            ['code' => 'M0754', 'name' => 'Database Design'],
            ['code' => 'M0774', 'name' => 'Data Warehouse'],
            ['code' => 'M0864', 'name' => 'Programming I'],
            ['code' => 'M0874', 'name' => 'Programming II'],
            ['code' => 'M0884', 'name' => 'Advanced Web Based Programming'],
            ['code' => 'M0924', 'name' => 'Applied Database I'],
            ['code' => 'M0934', 'name' => 'Applied Database II'],
            ['code' => 'M0944', 'name' => 'Applied Database III'],
            ['code' => 'MDIA6043', 'name' => 'New Media I'],
            ['code' => 'MDIA7012', 'name' => 'New Media I'],
            ['code' => 'MDIA7017', 'name' => 'New Media'],
            ['code' => 'MKTG6118', 'name' => 'Digital Marketing'],
            ['code' => 'MOBI6002', 'name' => 'Mobile Object Oriented Programming'],
            ['code' => 'MOBI6006003', 'name' => 'Mobile Community Solution'],
            ['code' => 'MOBI6006', 'name' => 'Mobile Community Solution'],
            ['code' => 'MOBI6009001', 'name' => 'Mobile Multimedia Solution'],
            ['code' => 'MOBI6009', 'name' => 'Mobile Multimedia Solution'],
            ['code' => 'MOBI6012001', 'name' => 'Web Design'],
            ['code' => 'MOBI6012', 'name' => 'Web Design'],
            ['code' => 'MOBI6021', 'name' => 'Mobile Programming'],
            ['code' => 'MOBI6026', 'name' => 'Mobile Cloud Computing'],
            ['code' => 'MOBI6027', 'name' => 'Mobile Programming'],
            ['code' => 'MOBI6059', 'name' => 'Mobile Programming'],
            ['code' => 'S1072', 'name' => 'Algorithm and Programming'],
            ['code' => 'T0016', 'name' => 'Algorithm and Programming'],
            ['code' => 'T0026', 'name' => 'Data Structures'],
            ['code' => 'T0044', 'name' => 'Object Oriented Programming'],
            ['code' => 'T0053', 'name' => 'Web Programming'],
            ['code' => 'T0063', 'name' => 'Visual Programming'],
            ['code' => 'T0074', 'name' => 'Computer Graph'],
            ['code' => 'T0084', 'name' => 'Human and Computer Interaction'],
            ['code' => 'T0091', 'name' => 'Multimedia System Laboratory'],
            ['code' => 'T0091', 'name' => 'Praktikum Sistem Multimedia'],
            ['code' => 'T0123', 'name' => 'OO Software Engineering'],
            ['code' => 'T0144', 'name' => 'Advanced Topics in Software Engineering'],
            ['code' => 'T0206', 'name' => 'Database Systems'],
            ['code' => 'T0213', 'name' => 'Web Database'],
            ['code' => 'T0233', 'name' => 'Data Warehouse'],
            ['code' => 'T0243', 'name' => 'Geographical Information System'],
            ['code' => 'T0273', 'name' => 'Expert Systems'],
            ['code' => 'T0283', 'name' => 'Computer Vision'],
            ['code' => 'T0293', 'name' => 'Neuro Computing'],
            ['code' => 'T0316', 'name' => 'Operating System'],
            ['code' => 'T0403', 'name' => 'Current Popular IT I'],
            ['code' => 'T0413', 'name' => 'Current Popular IT II'],
            ['code' => 'T0423', 'name' => 'Current Popular IT III'],
            ['code' => 'T0456', 'name' => 'Algorithm & OOP Methods'],
            ['code' => 'T0456', 'name' => 'Algorithm and Object Oriented Programming Methods'],
            ['code' => 'T0456', 'name' => 'Algoritma dan Metode Object Oriented Programming'],
            ['code' => 'T0464', 'name' => 'Algorithm and Programming'],
            ['code' => 'T0474', 'name' => 'Bahasa Pemrograman Object Oriented'],
            ['code' => 'T0484', 'name' => 'Pemrograman'],
            ['code' => 'T0553', 'name' => 'Multimedia Systems'],
            ['code' => 'T0553', 'name' => 'Sistem Multimedia'],
            ['code' => 'T0593', 'name' => 'Human and Computer Interaction'],
            ['code' => 'T0616', 'name' => 'Algoritma dan Pemrograman'],
            ['code' => 'T0672', 'name' => 'Prak. Bahasa Pemrograman Visual'],
            ['code' => 'T0693', 'name' => 'Current Popular IT IV'],
            ['code' => 'T0732', 'name' => 'Sistem Multimedia'],
            ['code' => 'T0773', 'name' => 'Database Design'],
            ['code' => 'T0934', 'name' => 'Multimedia Programming Foundation'],
            ['code' => 'T0944', 'name' => 'Game Design and Programming'],
            ['code' => 'T0952', 'name' => 'Multimedia 3D Modelling and Animation'],
            ['code' => 'T0974', 'name' => 'Algorithm and Object Oriented Programming Methods I'],
            ['code' => 'T0974', 'name' => 'Algoritma dan Metode Object Oriented Programming I'],
            ['code' => 'T0984', 'name' => 'Algorithm and Object Oriented Programming Methods II'],
            ['code' => 'T0984', 'name' => 'Algoritma dan Metode Object Oriented Programming II'],
            ['code' => 'T0994', 'name' => 'Mobile Object Oriented Programming'],
            ['code' => 'T1034', 'name' => 'Mobile Community Solution'],
            ['code' => 'T1044', 'name' => 'Mobile Push Technology Solution'],
            ['code' => 'T1064', 'name' => 'Mobile Multimedia Solution'],
            ['code' => 'T1094', 'name' => 'Web Design'],
            ['code' => 'T1104', 'name' => 'Mobile Cloud Computing'],
            ['code' => 'T1204', 'name' => 'Multimedia in Games'],
            ['code' => 'T1214', 'name' => 'Object Oriented Game Programming'],
            ['code' => 'T1244', 'name' => '2D Game Programming'],
            ['code' => 'T1254', 'name' => 'GPU and Computer Graphics Programming'],
            ['code' => 'T1263', 'name' => 'Mobile Game Programming'],
            ['code' => 'T1273', 'name' => 'Game Audio Engineering'],
            ['code' => 'T1324', 'name' => '3D Game Programming'],
            ['code' => 'T1332', 'name' => '3D Modelling and Animation'],
            ['code' => 'T1364', 'name' => 'Web Game Programming'],
            ['code' => 'T1392', 'name' => 'Advanced Object Oriented Programming'],
            ['code' => 'T1404', 'name' => 'Mobile Programming'],
            ['code' => 'T1446', 'name' => 'Algorithm and Programming'],
            ['code' => 'T1456', 'name' => 'Object Oriented Programming'],
            ['code' => 'T1464', 'name' => 'Programming for Business'],
            ['code' => 'T1912', 'name' => '2D Animation'],
            ['code' => 'T1994', 'name' => '2D Game Programming'],
            ['code' => 'T2102', 'name' => 'Storyboarding & Concept Art'],
            ['code' => 'T2114', 'name' => 'Mobile & Web Game Programming'],
            ['code' => 'T2122', 'name' => '3D Modelling for Games'],
            ['code' => 'T2172', 'name' => 'Game Engine Programming'],
            ['code' => 'T2334', 'name' => 'Web Database'],
            ['code' => 'T2344', 'name' => 'Computer Vision'],
            ['code' => 'T2354', 'name' => 'Network Security'],
            ['code' => 'T2363', 'name' => 'Multimedia Programming Foundation'],
            ['code' => 'T2372', 'name' => 'Database Design'],
            ['code' => 'T2382', 'name' => 'Expert Systems'],
            ['code' => 'T2392', 'name' => 'Network Management'],
            ['code' => 'T2533', 'name' => 'Current Popular IT V'],
            ['code' => 'U1056', 'name' => 'New Media I'],
            ['code' => 'U1066', 'name' => 'New Media II'],
            ['code' => 'U1616', 'name' => 'New Media II'],
            ['code' => 'Z0004', 'name' => '[COMP6178]Introduction to Programming'],
            ['code' => 'Z0081', 'name' => '[COMP6047]Algorithm and Programming'],
            ['code' => 'Z0267', 'name' => '[COMP6175]Object Oriented Programming'],
            ['code' => 'Z0840', 'name' => '[COMP6064]Geographical Information System'],
        ];

        foreach ($subjects as $subject) {
            $data = collect($subject)->merge(['id' => Str::uuid()])->all();
            Subject::create($data);
        }
    }
}
